version: '3'

services:
  php-fpm:
    container_name: container_php
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ../../../application:/var/www
      - ./php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"

  nginx:
    container_name: container_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ../../../application:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ../../logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"